name: Update Contributors List

on:
  push:
    branches:
      - main

jobs:
  update-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get contributors and their merged PRs
        id: contributors
        run: |
          CONTRIBUTORS_MD="CONTRIBUTORS.md"
          echo "# Contributors" > $CONTRIBUTORS_MD
          echo "" >> $CONTRIBUTORS_MD

          # Fetch contributors
          CONTRIBUTORS=$(curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/contributors?per_page=100" | jq -r '.[].login')

          # Iterate over contributors
          for contributor in $CONTRIBUTORS; do
            echo "## $contributor" >> $CONTRIBUTORS_MD
            echo "" >> $CONTRIBUTORS_MD

            # Fetch PRs merged by the contributor
            PRS=$(curl -s "https://api.github.com/search/issues?q=is:pr+is:merged+author:$contributor+repo:${GITHUB_REPOSITORY}" | jq -r '.items[].title')

            # Iterate over PRs
            for pr in $PRS; do
              echo "- $pr" >> $CONTRIBUTORS_MD
            done

            echo "" >> $CONTRIBUTORS_MD
          done

          git add $CONTRIBUTORS_MD
          git commit -m "Update CONTRIBUTORS.md with new contributors"
          git push

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CONTRIBUTORS.md
          git commit -m "Update CONTRIBUTORS.md with new contributors"
          git push